services:
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: app-phpmyadmin
      environment:
        PMA_HOST: application-db
        MYSQL_ROOT_PASSWORD: segreta
      ports:
        - "7070:80" 
      networks:
      - backend_default

networks:
  backend_default:
    external: true 